#!/usr/bin/env bash

MESSAGE="$1"
VERSION="$2"

SCRIPT_PATH="$0"; while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
. "$(dirname "$SCRIPT_PATH")/modules/functions.sh"

. "$HOOKS_DIR/modules/validate-changelog.sh"
if [ $? -ne 0 ]; then
    exit 1
fi

. "$HOOKS_DIR/modules/format-tag-message.sh"
if [ $? -ne 0 ]; then
    exit 1
fi

echo "${MESSAGE}"
exit 0
